name: First Workflow Example

on: push

jobs:
    example_job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo "My first Github Action Workflow"
          
        - name: List files
          run: ls

        - name: Read file
          run: cat README.md